services:
  blog:
    build: .
    #image: registry.gitlab.matthewrease.net/matthew/blog-docker:latest
    ports:
      - "8080:80"  # Expose port 8080 for your app
    environment:
      - MYSQL_HOST=db
      #- MYSQL_USER=blog
      #- MYSQL_PASSWORD=blog
      #- MYSQL_DATABASE=blog
      - USE_CSP=false     # Content Security Policy headers
      - REBUILD_DB=true   # clears database on every run
      - UPDATE_DB=always  # set to manual if you wish to run `update db` yourself
    #volumes:
    #  - blog_posts:/app/posts
    #  - blog_images:/app/blog/static/images
    #  - /path/to/icon:/app/blog/static/icon.webp
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Set the root password for the MariaDB container
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog
      MYSQL_DATABASE: blog
    volumes:
      - db_data:/var/lib/mysql
    #ports:
    #  - "3306:3306"  # Expose port 3306 for database access (optional)
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "--host=127.0.0.1", "--user=root", "--password=rootpassword"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  db_data:
    driver: local
